#!/bin/bash
yum update -y
yum install -y docker git awscli jq
service docker start
usermod -aG docker ec2-user
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
cd /home/ec2-user && git clone https://github.com/YOURREPO/cloudvpn-custom.git && cd cloudvpn-custom/wireguard-docker && docker-compose up -d
